{
 "title": "S.M.A.R.T.",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(smart_disk_health,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Age", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Power on time",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "smart_power_on_hours_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Start-stop-count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "smart_start_stop_count_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Load cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "smart_load_cycle_count{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "LBAs written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "smart_written_lbas_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "LBAs read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "smart_read_lbas_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Power cycles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "smart_power_cycle_count_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smart_case_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}}) case temperature"
    },
    {
     "expr": "smart_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}}) temperature"
    }
   ]
  },
  {
   "title": "Seek time performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "smart_seek_time_performance{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Throughput performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "smart_throughput_performance{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Pending sectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "smart_pending_sectors{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "System error",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "smart_system_error{instance=\"$instance\"}",
     "legendFormat": "State"
    }
   ]
  },
  {
   "title": "Metric errors",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "smart_metric_error{instance=\"$instance\"}",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "Access error",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "smart_access_error{instance=\"$instance\"}",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "Disk health",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "smart_disk_health{instance=\"$instance\"}",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "Bad blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "smart_runtime_bad_blocks_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Uncorrectable sectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "smart_uncorrectable_sectors{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "CRC errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "smart_udma_crc_error_count_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Uncorrectable errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "smart_uncorrectable_errors_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Reallocated sectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "targets": [
    {
     "expr": "smart_reallocated_sectors_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Reallocation events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "smart_reallocation_events_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Spin retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "targets": [
    {
     "expr": "smart_spin_retries_total{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Raw read error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "smart_raw_read_error_rate{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Seek error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
   "targets": [
    {
     "expr": "smart_seek_error_rate{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  },
  {
   "title": "Spin-up time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "smart_spin_up_time{instance=\"$instance\"}",
     "legendFormat": "{{drive}} ({{family}})"
    }
   ]
  }
 ]
}